In [ ]:
import pandas as pd

df = pd.read_csv('/synthetic_online_retail_data.csv')
df.head()

,customer_id,order_date,product_id,category_id,category_name,product_name,quantity,price,payment_method,city,review_score,gender,age
0,13542,2024-12-17,784,10,Electronics,Smartphone,2,373.36,Credit Card,New Oliviaberg,1.0,F,56
1,23188,2024-06-01,682,50,Sports & Outdoors,Soccer Ball,5,299.34,Credit Card,Port Matthew,NaN,M,59
2,55098,2025-02-04,684,50,Sports & Outdoors,Tent,5,23.00,Credit Card,West Sarah,5.0,F,64
3,65208,2024-10-28,204,40,Books & Stationery,Story Book,2,230.11,Bank Transfer,Hernandezburgh,5.0,M,34
4,63872,2024-05-10,202,20,Fashion,Skirt,4,176.72,Credit Card,Jenkinshaven,1.0,F,33

In [ ]:
df.shape

(1000, 13)

In [ ]:
df.dtypes

customer_id         int64
order_date         object
product_id          int64
category_id         int64
category_name      object
product_name       object
quantity            int64
price             float64
payment_method     object
city               object
review_score      float64
gender             object
age                 int64
dtype: object

In [ ]:
df.isnull().sum()

customer_id         0
order_date          0
product_id          0
category_id         0
category_name       0
product_name        0
quantity            0
price               0
payment_method      0
city                0
review_score      201
gender            103
age                 0
dtype: int64

In [ ]:
df.describe

<bound method NDFrame.describe of      customer_id  order_date  product_id  category_id       category_name  \
0          13542  2024-12-17         784           10         Electronics
1          23188  2024-06-01         682           50   Sports & Outdoors
2          55098  2025-02-04         684           50   Sports & Outdoors
3          65208  2024-10-28         204           40  Books & Stationery
4          63872  2024-05-10         202           20             Fashion
..           ...         ...         ...          ...                 ...
995        67967  2024-05-04         965           40  Books & Stationery
996        99828  2024-09-12         510           40  Books & Stationery
997        92290  2024-11-06         445           10         Electronics
998        61427  2024-09-17         410           10         Electronics
999        20658  2024-11-06         177           40  Books & Stationery

    product_name  quantity   price    payment_method            city  \
0     Smartphone         2  373.36       Credit Card  New Oliviaberg
1    Soccer Ball         5  299.34       Credit Card    Port Matthew
2           Tent         5   23.00       Credit Card      West Sarah
3     Story Book         2  230.11     Bank Transfer  Hernandezburgh
4          Skirt         4  176.72       Credit Card    Jenkinshaven
..           ...       ...     ...               ...             ...
995     Notebook         3  495.24  Cash on Delivery      Hodgemouth
996   Story Book         5  427.73       Credit Card     Douglastown
997   Smartphone         5  354.64     Bank Transfer  New Amberville
998       Laptop         4  221.54  Cash on Delivery        New Sean
999          Pen         3  196.97  Cash on Delivery    North Kelsey

     review_score gender  age
0             1.0      F   56
1             NaN      M   59
2             5.0      F   64
3             5.0      M   34
4             1.0      F   33
..            ...    ...  ...
995           NaN    NaN   30
996           3.0      F   72
997           NaN      M   49
998           3.0      M   71
999           1.0      M   34

[1000 rows x 13 columns]>

In [ ]:
df['gender'].fillna(df['gender'].mode()[0], inplace=True)

/tmp/ipykernel_3326/1062339567.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(df['gender'].mode()[0], inplace=True)

In [ ]:
df['review_score'].fillna(df['review_score'].mean(), inplace=True)

/tmp/ipykernel_3326/516660258.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_score'].fillna(df['review_score'].mean(), inplace=True)

In [ ]:
df.isnull().sum()

customer_id       0
order_date        0
product_id        0
category_id       0
category_name     0
product_name      0
quantity          0
price             0
payment_method    0
city              0
review_score      0
gender            0
age               0
dtype: int64